### ISSUE TITLE
Can I Check More than One FINDpubkey at the Same Time?

### ISSUE THREAD

**Issue by steve17dg** [phrutis/Collider#13]
Hi
Good afternoon
Is there anyway I can check more than one FINDpubkey at the same time? I tried to use the function of "-infile" but it didn't work.
I tried also to use two public addresses instead of one "Collider.exe -t 512 -b 72 -p 306 -pk 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5e0000000000000000 -pke 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5effffffffffffffff -w 30 -htsz 28 -pb 03c5bcdd76b64cbbd8212080fe5efa9bf577cdcaac9f5853b216e71723ec3aca19 02CEB6CBBCDBDF5EF7150682150F4CE2C6F4807B349827DCDBDD1F2EFA885A2630", but it didn't work. Any help please?

**Comment by phrutis** [comment]
The collider looks for only one public key.

You can set a list of public keys -infile list.txt

After passing the specified range of the private key, the program will restart with a new public key from the list.

**Comment by phrutis** [comment]
If the range of private keys is small, you can search for a large list in Rotor-Cuda mode xPoints

**Comment by steve17dg** [comment]
Ok. Thanks :)

**Comment by steve17dg** [comment]
Any updates about my request?
