### ISSUE TITLE
How i can get compressed/uncompressed public key from spesific address?

### ISSUE THREAD

**Issue by syllxvestern** [phrutis/Collider#15]

**Comment by phrutis** [comment]
If the address has an outgoing transaction, you can get https://blockchain.info/q/pubkeyaddr/1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ like this.
If there were no outgoing transactions, this is not possible.

**Comment by syllxvestern** [comment]
Thanks for your reply, i know it from forum yesterday, im sorry for dumb question😅
