### ISSUE TITLE
Port Code to Linux

### ISSUE THREAD

**Issue by GilfoyleGit** [phrutis/Collider#3]
Hi,

Its possible to port this code to linux?

Thanks

**Comment by phrutis** [comment]
Hey! The author has already been asked what to do under linux. He didn't want to.
I do not have linux as well as PureBasic knowledge to rebuild the project.

Try to assemble it yourself! 
Download PureBasic v5.31 for linux and try build

**Comment by AliGindahouseGit** [comment]
Hey! thanks for your answer.

Well without changing the code, well the syntax of all code its for pure basic 5.31, on newer releases the code has to be changed I got this result using libcuda.so 11.0:

 ./purebasic.out
./purebasic.out: Symbol `exit' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceGet' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceGet' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuCtxCreate_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuCtxCreate_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuModuleLoadData' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuModuleGetFunction' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuFuncSetCacheConfig' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemGetInfo_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemGetInfo_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemAlloc_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuParamSetSize' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuParamSeti' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuParamSeti' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuFuncSetBlockShape' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyHtoD_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyHtoD_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyHtoD_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyHtoD_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyHtoD_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuLaunchGrid' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuCtxSynchronize' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyDtoH_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemcpyDtoH_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuMemFree_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuCtxDestroy_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuCtxDestroy_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuInit' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceGetCount' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceGetName' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceTotalMem_v2' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceComputeCapability' causes overflow in R_X86_64_PC32 relocation
./purebasic.out: Symbol `cuDeviceGetAttribute' causes overflow in R_X86_64_PC32 relocation
Segmentation fault (core dumped)

I need to figure out this issue. 

Thanks

**Comment by AliGindahouseGit** [comment]
Whats the cuda.lib version you use to compile on Windows?

**Comment by phrutis** [comment]
I have CUDA [10.22](https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork) for Windows x64
The requested file cuda.lib was found through a search inside the pc

**Comment by phrutis** [comment]
I have built in increasing the window size, maybe there will be a compiler error on linux. Try building 1.7.3 version or sources.

**Comment by AliGindahouseGit** [comment]
I got it compiled on linux but:

./collider -t 512 -b 204 -p 492 -w 30 -htsz 28
  Collider      : v1.7.9 (02.12.2021 Random TEST version)
  USE GPUs      : 1
  GPU           : NVIDIA GeForce RTX 2080 Ti (10859.6875/11019 MB)
  Try parameters: -t 512 -b 204 -p 492 -w 30 -htsz 28 [10848.750 MB] Gen RAM[28672 MB]

**Comment by phrutis** [comment]
Try version 1.7.3 or [original](https://github.com/Etayson/BSGS-cuda)
Perhaps tables are being created and you need to wait. Look at the state of the RAM if it is consumed, then it works

**Comment by AliGindahouseGit** [comment]
Yes I tried your fork and the original, same behavior on both... after the output I described above it exits to console

**Comment by phrutis** [comment]
A little-studied language can ask a Purebasic programmers forum?
I can’t help or suggest here.

**Comment by AliGindahouseGit** [comment]
Thank you. It may have to do with cuda instructions used on this code.
